// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ltyosoaycfrxaxeywnwq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx0eW9zb2F5Y2ZyeGF4ZXl3bndxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM0MzExNjIsImV4cCI6MjA2OTAwNzE2Mn0.C2niIGitrD-KIFiVWmvYdI5gzbDckh6z6rc5lp1T4V4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});